name = 'cloudflare-worker-template'
type = 'webpack'
routes = ['your.subdomain.workers.dev']
workers_dev = true
webpack_config = 'webpack.config.js'
compatibility_date = '2021-12-14'

[vars]
TEST_VAR = 'test var'

# [[kv_namespaces]]
# wrangler kv:namespace create "NAMESPACE" --preview
# binding = ''
# id = ''
# preview_id = ''